
//valores primitivos
40 //entero

"Deiwin MOnsalve" //strign o texto

true
false //boleanos

null
undefined //valor reservados como nulo para despues utilizar un valor

//valores de tipo objetos o no primitivos

[1, 2, 3] //array de tipo objecto
{ nombre: "Deiwin"} //valor tipo objecto
//////
// Basic or primitive values
//////

// Int values
40

// String values
"Josué Tamayo"

// Boolean values
true
false

// Empty or placeholder values
// It is important to avoid (try to not use) undefined value, it's a reserved value generated by JS
null
undefined


//////
// Object or no primitive values
//////

// Array values
[1,2,3]

// Object values
{ nombre: 'Josue'}